@url = http://localhost:7070

###

GET {{url}}/tickets?method=allTickets

###

GET {{url}}/private/me
Content-Type: application/json
Authorization: Bearer 0856c858-2692-43ff-ba8c-12206a868156


###

POST {{url}}/auth
Content-Type: application/json

{ "login": "vasya", "password": "password" }

###

DELETE {{url}}/tickets/2
